#!/bin/sh
#
# Simple activemq init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.
#
# chkconfig: - 85 15
# description: ActiveMQ Server
# processname: activemq

EXEC="/opt/activemq/bin/activemq"

case "$1" in
    start)
        echo "Starting activemq server..."
        $EXEC start
        echo "Activemq server started"
        ;;
    stop)
        echo "Stoping activemq server..."
        $EXEC stop
        echo "Activemq stopped"
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
